### PR TITLE
Add minimal travis config

### PR DESCRIPTION
**Pull request by njsmith**
Just to let us run tests until we get tox working again

### CODE REVIEW

**Comment by njsmith** [comment]
It looks like we have one "real" failure on 3.6 that I haven't dug into yet, and then on 3.7-dev something is going Very Wrong. (Lots of failures, then it freezes... and before that it complains about an unawaited coroutine, which is *extremely* weird because there shouldn't be any coroutines in the test suite right now! Maybe something is going wrong with the syncifying script?)

Possibly the thing to do is to mark the one failure as xfail and disable 3.7 for now. Lmk if you have any thoughts.

**Comment by njsmith** [comment]
...not sure what's going on here. I definitely saw a 3.6 failure yesterday, but now it seems to be working fine, and all the old logs say it was working fine too? Not sure what I was looking at...

**Comment by njsmith** [comment]
And on a closer look, the 3.7 errors might have to do with getting these errors when installing a bunch of the dependencies:

```
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-7m3x2g4o/zope.interface/setup.py", line 142, in <module>
      keywords=['interface', 'components', 'plugins'],
    File "/home/travis/build/njsmith/urllib3/test-venv-py37/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/opt/python/3.7-dev/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/python/3.7-dev/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/python/3.7-dev/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/travis/build/njsmith/urllib3/test-venv-py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/travis/build/njsmith/urllib3/test-venv-py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/travis/build/njsmith/urllib3/test-venv-py37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for zope.interface
```

Anyway this isn't worth worrying about right now, and things seem to be passing on 3.5 and 3.6, so I guess this is ready to merge.

**Comment by pquentin** [comment]
The assertion error is because the wheel package version did not support 3.7, so pip fallbacked to building the wheel. There's no consequence, but it does add noise to the build.

I also saw the 3.6 failure on Travis :) I'm not sure this one is fully deterministic because I saw it failing sometimes locally : skipping it might be safer. We'll do it when we see it fail again.

I'll be happy to merge when all the checks are green, which is not the case yet?

**Comment by njsmith** [comment]
Ah-hah, this build failed the same way as I saw last night: https://travis-ci.org/njsmith/urllib3/jobs/354928758

So I guess we have an intermittent failure in `TestProxyManager.test_retries` -- it's expecting

```
        self.assertRaises(ProxyError, conn.urlopen, 'GET',
                          'http://www.google.com',
>                         retries=False)
```

but gets:

```
E           urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteProtocolError("can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE",))
```

Looks like some issue with h11 confusing urllib3 about what kind of exception to report...

**Comment by njsmith** [comment]
> The assertion error is because the wheel package version did not support 3.7, so pip fallbacked to building the wheel. There's no consequence, but it does add noise to the build.

Oh, I see, you're right:

```
  Running setup.py install for zope.interface ... done
  Running setup.py install for cffi ... done
  Running setup.py install for cryptography ... done
  Running setup.py install for twisted ... done
```

So there's some *other* reason why this is blowing up on 3.7 :-).

**Comment by njsmith** [comment]
(Still fighting with windows here)

**Comment by njsmith** [comment]
So the issue in Windows seems to be that running 'setup.py build' somehow
does *not* generate the _sync directory. I am kind of baffled by this, but
there it is.

I can keep debugging, but virtualbox just took down my whole machine so it
will be a bit :-)

**Comment by pquentin** [comment]
Oh, and one issue to watch for is that runtests.py installs twine which depends on urllib3 indirectly.

**Comment by pquentin** [comment]
`pytest -v` can be helpful to see a blocking text, because you will get a new line for each test if I recall correctly.

**Comment by njsmith** [comment]
Sure, let's give it a try...

**Comment by njsmith** [comment]
Current status:

* can't run tests on my windows VM because I don't have MSVC installed

* appveyor is running tests, but AFAICT it's *not printing the end of the pytest logs*, it just cuts off in the middle for no apparent reason and then reports that pytest has exited with non-zero status

**Comment by njsmith** [comment]
Progress: using `pytest-random-order`, I now know that it's not that appveyor is losing some logs at the end of the run, it's that on windows, `test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_https_proxy_pool_timeout` is causing pytest to abort with an error and no particular output.

**Comment by njsmith** [comment]
Got it! These tests are relying on functionality we haven't implemented it yet. In the tests, urllib3 is using [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout) to enforce a timeout on these tests, e.g. `pytest.mark.timeout(0.5)`. We're hitting that timeout. On Unix, this causes the test to fail, so they're marked xfail. But on Windows, pytest-timeout doesn't have a way to make an individual test fail when we hit the overall timeout, so it just aborts the process (this is the documented behavior).

So for all the tests with `pytest.mark.xfail` + `pytest.mark.timeout` I think we need to switch to skipping.

**Comment by njsmith** [comment]
OK, I think this is finally ready to merge!

**Comment by pquentin** [comment]
Awesome detective work! 👏

**Comment by pquentin** [comment]
By the way, why don't we write bytecode?

**Comment by njsmith** [comment]
Python is not always very clever about figuring out which bytecode files are usable when switching between interpreters and OSes and other such shenanigans. I'm not sure having that there will actually help anything, but I got some errors from pytest about .pyc files so I threw it in on the theory that it rarely hurts for this kind of use case.

**Comment by njsmith** [comment]
Hmm, looking more closely the error I got was:
```
 ERROR collecting test-venv-cp36m-win_amd64/Lib/site-packages/tornado/test/web_test.py 
import file mismatch:
imported module 'tornado.test.web_test' has this __file__ attribute:
  /home/njs/src/urllib3/test-venv-cp35m-linux_x86_64/lib/python3.5/site-packages/tornado/test/web_test.py
which is not the same as the test file we want to collect:
  /home/njs/src/urllib3/test-venv-cp36m-win_amd64/Lib/site-packages/tornado/test/web_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

and I guess the problem here is that pytest is scanning all the venv dirs looking for tests.

**Pull request merged**
