### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by njsmith**
CC @pquentin

### CODE REVIEW

**Comment by njsmith** [comment]
Going to go ahead and merge this since I think it's trivial, but figured I'd put up a PR in case you wanted to see it.

**Comment by pquentin** [comment]
Thanks for the pull request!

Using lower case in the version number would avoid the following warning: `UserWarning: Normalizing '2.0.dev0+BLEACH.SPIKE.PROOF.OF.CONCEPT.DONT.USE' to '2.0.dev0+bleach.spike.proof.of.concept.dont.use'` when using `python setup.py build`, but maybe the whole point was to show the warning?

I'm afraid using `requires-dist` in setup.cfg is not equivalent to the `install_requires` setup() parameter. [PEP 345](https://www.python.org/dev/peps/pep-0345/#requires-dist-multiple-use) mentions distutils, and `pip install .` does not install h11 without `install_requires`. Maybe both are useful? I don't know enough about Python packaging to be more precise, sorry.

**Comment by pquentin** [comment]
(Even though it was merged, I figured out this is still the best place to discuss about the changes.)

**Comment by njsmith** [comment]
What the heck. I wasn't looking at `pip install .`, just `bdist_wheel`. And for `bdist_wheel`, `requires-dist` in `setup.cfg` *does* put the right metadata into the wheel generated by `bdist_wheel`, and what we were doing before didn't (just printed a warning that `setup.cfg` was overwriting the settings in `setup.py`). I guess we need it in both places? Why does urllib3 even have this setup.cfg?

**Comment by njsmith** [comment]
Just pushed changes to lowercase the version number, and put h11 back in setup.py so you can h11 while you h11.

**Comment by pquentin** [comment]
From what I can observe, we do need both, and this is also why urllib3 has both extras_requires and provides-extra.

Life is indeed full of mysteries. 😄

**Comment by njsmith** [comment]
I'm pretty sure if they deleted the stuff from `setup.cfg` then everything would use `setup.py` and Just Work. But I am not going to stress about this right now :-)

**Pull request merged**
